apiVersion: apps/v1
kind: Deployment
metadata:
  name: consentapidev
  labels:
    app: consentapidev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consentapidev
  template:
    metadata:
      labels:
        app: consentapidev
    spec:
      containers:
      - name: consentapidev
        image: datalakeregistrydev.azurecr.io/datalakeimgdev:dev_v1
        ports:
        - containerPort: 80
