apiVersion: apps/v1
kind: Deployment
metadata:
  name: consentapidemo2-deployment
  labels:
    app: consentapidemo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consentapidemo2
  template:
    metadata:
      labels:
        app: consentapidemo2
    spec:
      containers:
      - name: consentapidemo2
        image: datalakeregistrydev.azurecr.io/datalakeimgdev:dev_v1
        ports:
        - containerPort: 80
